# Generated by Django 5.1.8 on 2025-05-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0031_alter_spatialdatacalculation_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs', models.CharField(choices=[('EPSG:3577', 'GDA94 / Australian Albers'), ('EPSG:9473', 'GDA2020 / Australian Albers')], default='EPSG:3577', max_length=10)),
            ],
        ),
    ]
